services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: nina-postgres
    environment:
      POSTGRES_USER: nina
      POSTGRES_PASSWORD: nina
      POSTGRES_DB: nina
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nina-network

  openai-edge-tts:
    image: travisvn/openai-edge-tts:latest
    container_name: openai-edge-tts
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - API_KEY=your_api_key

networks:
  nina-network:
    driver: bridge

volumes:
  pgdata:
