"""change embedding dimension

Revision ID: e69ea76bb1da
Revises: 61f68fb18628
Create Date: 2026-08-13 22:09:16.019925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector


# revision identifiers, used by Alembic.
revision: str = 'e69ea76bb1da'
down_revision: Union[str, Sequence[str], None] = '61f68fb18628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=2048),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=2048),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=False)
    # ### end Alembic commands ###
